name: PHPUnit Tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  drupal-tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/salsadigitalauorg/drupal-testing:php8.3
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run PHPUnit tests
      run: |
        docker build -t scaffold-testing -f .github/drupal/Dockerfile .
        docker run --rm -v $(pwd):/app scaffold-testing \
          bash -c "composer install --no-interaction && ./vendor/bin/phpunit \
          --configuration=.github/drupal/phpunit.xml \
          .github/drupal/tests/Unit/Installer/InstallerTest.php"
