name: PHPUnit Tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  drupal-tests:
    runs-on: ubuntu-latest
    container:
      image: php:8.3-cli

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        apt-get update && apt-get install -y \
          git \
          unzip \
          libzip-dev \
          && docker-php-ext-install zip

    - name: Install Composer
      run: |
        curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

    - name: Run PHPUnit tests
      run: |
        composer install --no-interaction
        ./vendor/bin/phpunit \
          --configuration=phpunit.xml \
          tests/Unit/Installer/InstallerTest.php
