name: Test Scaffold Testing Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: php:8.3-cli

    steps:
      - uses: actions/checkout@v2

      - name: Install system dependencies
        run: |
          apt-get update && apt-get install -y \
            git \
            unzip \
            libzip-dev \
            && docker-php-ext-install zip

      - name: Install Composer
        run: |
          curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

      - name: Run tests
        run: |
          # Copy phpunit.xml to the working directory
          cp $GITHUB_WORKSPACE/phpunit.xml phpunit.xml

          # Install dependencies
          composer install --no-interaction --no-progress

          # Run PHPUnit tests
          ./vendor/bin/phpunit \
            -v \
            --configuration phpunit.xml \
            tests/Unit/ 